version: "3.3"

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  redis_secure:
    image: "redis:alpine"
    volumes:
      - ./acceptance-tests/redis-confs:/usr/local/etc/redis
    ports:
      - target: 6380
        published: 6380
        protocol: tcp
        mode: host
    entrypoint: ["/usr/local/bin/redis-server", "/usr/local/etc/redis/with_password.conf"]
  tests:
    image: "alpine:latest"
    volumes:
      - ./acceptance-tests:/acceptance-tests
      - ./bin/generator:/generator
      - ./bin/redis-dump-go:/redis-dump-go
    depends_on:
      - "redis"
      - "redis_secure"
    working_dir: /acceptance-tests
    entrypoint: ["/acceptance-tests/entrypoint.sh"]