name: ci
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: test
        run: make docker-test

      - name: build
        run: make goreleaser-build-static

      - name: build-generator
        run: make docker-build-generator-static

      - name: acceptance-tests
        run: make acceptance-tests

  goreleaser:
    runs-on: ubuntu-latest
    needs:
      - test
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # https://github.com/goreleaser/goreleaser-action/issues/56

      - name: goreleaser
        run: |
          echo "${{ github.token }}" | docker login https://ghcr.io -u ${GITHUB_ACTOR} --password-stdin
          make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
